### ISSUE TITLE
Can't compile with GCC 4.7.0

### ISSUE THREAD

**Issue by GoogleCodeExporter** [byzhang/rapidjson#29]
```
When compiling with GCC 4.7.0 under windows with MinGW/MSYS the following 
errors are given:

../../include/rapidjson/document.h: In instantiation of 
'rapidjson::GenericDocument<Encoding, Allocator>& 
rapidjson::GenericDocument<Encoding, Allocator>::ParseStream(Stream&) [with 
unsigned int parseFlags = 1u; Stream = 
rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Encoding = 
rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; 
rapidjson::GenericDocument<Encoding, Allocator> = 
rapidjson::GenericDocument<rapidjson::UTF8<> >]':
../../include/rapidjson/document.h:726:54:   required from 
'rapidjson::GenericDocument<Encoding, Allocator>& 
rapidjson::GenericDocument<Encoding, 
Allocator>::ParseInsitu(rapidjson::GenericDocument<Encoding, Allocator>::Ch*) 
[with unsigned int parseFlags = 0u; Encoding = rapidjson::UTF8<>; Allocator = 
rapidjson::MemoryPoolAllocator<>; rapidjson::GenericDocument<Encoding, 
Allocator> = rapidjson::GenericDocument<rapidjson::UTF8<> >; 
rapidjson::GenericDocument<Encoding, Allocator>::Ch = char]'
JSONLoader.cpp:27:29:   required from here
../../include/rapidjson/document.h:706:4: error: 'RawAssign' was not declared 
in this scope, and no declarations were found by argument-dependent lookup at 
the point of instantiation [-fpermissive]
../../include/rapidjson/document.h:706:4: note: declarations in dependent base 
'rapidjson::GenericValue<rapidjson::UTF8<> >' are not found by unqualified 
lookup
../../include/rapidjson/document.h:706:4: note: use 'this->RawAssign' instead
../../include/rapidjson/document.h: In instantiation of 
'rapidjson::GenericDocument<Encoding, Allocator>& 
rapidjson::GenericDocument<Encoding, Allocator>::ParseStream(Stream&) [with 
unsigned int parseFlags = 0u; Stream = 
rapidjson::GenericStringStream<rapidjson::UTF8<> >; Encoding = 
rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; 
rapidjson::GenericDocument<Encoding, Allocator> = 
rapidjson::GenericDocument<rapidjson::UTF8<> >]':
../../include/rapidjson/document.h:737:35:   required from 
'rapidjson::GenericDocument<Encoding, Allocator>& 
rapidjson::GenericDocument<Encoding, Allocator>::Parse(const Ch*) [with 
unsigned int parseFlags = 0u; Encoding = rapidjson::UTF8<>; Allocator = 
rapidjson::MemoryPoolAllocator<>; rapidjson::GenericDocument<Encoding, 
Allocator> = rapidjson::GenericDocument<rapidjson::UTF8<> >; 
rapidjson::GenericDocument<Encoding, Allocator>::Ch = char]'
JSONLoader.cpp:29:23:   required from here
../../include/rapidjson/document.h:706:4: error: 'RawAssign' was not declared 
in this scope, and no declarations were found by argument-dependent lookup at 
the point of instantiation [-fpermissive]
../../include/rapidjson/document.h:706:4: note: declarations in dependent base 
'rapidjson::GenericValue<rapidjson::UTF8<> >' are not found by unqualified 
lookup
../../include/rapidjson/document.h:706:4: note: use 'this->RawAssign' instead
```

Original issue reported on code.google.com by `Peter.Di...@gmail.com` on 9 Jul 2012 at 5:44
- Merged into: #13

**Comment by GoogleCodeExporter** [comment]
```
../../include/rapidjson/document.h:706:4: note: use 'this->RawAssign' instead

i think it's obvious to fix.
still interested if there are other build errors, want to use this lib in my 
project.
```

Original comment by `igor.c...@gmail.com` on 11 Jul 2012 at 1:40

**Comment by GoogleCodeExporter** [comment]
```
Duplicate of issue 13, fixed by r55.
```

Original comment by `art...@push.am` on 16 Oct 2012 at 10:11

**Comment by GoogleCodeExporter** [comment]
Original comment by `milo...@gmail.com` on 13 Nov 2012 at 9:42
- Changed state: **Duplicate**
